In [19]:
import pandas as pd
from pathlib import Path
main_dict = {}

In [20]:
from tqdm import tqdm 

ngram1 = Path('slavic_review_data/SlavicStudiesCluster1991to2020/ngram1')
for file in tqdm(ngram1.iterdir(), total=len(list(ngram1.iterdir()))):
    text = file.read_text()
    for line in text.split('\n'):
        word=line.split('\t')[0]
        freq=line.split('\t')[-1]
        if freq == '':
            pass
        else:
            freq = int(freq)
            assert isinstance(freq, int)

        if word in main_dict.keys():
            main_dict[word] = main_dict[word] + freq
        else:
            main_dict[word] = freq

100%|██████████| 41251/41251 [00:41<00:00, 996.72it/s]

In [21]:
from tqdm import tqdm 

ngram2 = Path('slavic_review_data/SlavicStudiesCluster1991to2020/ngram2')
for file in tqdm(ngram2.iterdir(), total=len(list(ngram2.iterdir()))):
    text = file.read_text()
    for line in text.split('\n'):
        word=line.split('\t')[0]
        freq=line.split('\t')[-1]
        if freq == '':
            pass
        else:
            freq = int(freq)
            assert isinstance(freq, int)

        if word in main_dict.keys():
            main_dict[word] = main_dict[word] + freq
        else:
            main_dict[word] = freq

100%|██████████| 41251/41251 [01:49<00:00, 375.56it/s]

In [22]:
ngram3 = Path('slavic_review_data/SlavicStudiesCluster1991to2020/ngram3')
for file in tqdm(ngram3.iterdir(), total=len(list(ngram3.iterdir()))):
    text = file.read_text()
    for line in text.split('\n'):
        word=line.split('\t')[0]
        freq=line.split('\t')[-1]
        if freq == '':
            pass
        else:
            freq = int(freq)
            assert isinstance(freq, int)
        if word in main_dict.keys():
            main_dict[word] = main_dict[word] + freq
        else:
            main_dict[word] = freq

100%|██████████| 41251/41251 [01:59<00:00, 345.19it/s]

In [23]:
df= pd.DataFrame(main_dict.items(), columns=['word', 'freq'])

In [8]:
df.head().sort_values('freq', ascending=False)

         word    freq
1     russian  367337
2      russia  201074
0  university  120060
3          00   48639
4         eds   35248

In [9]:

hatebase = pd.read_csv('slavic_review_data/hatebase.csv')

In [10]:

common = pd.Series(list(set(df['word']) & set(hatebase['term'])))

In [11]:
common

0         bimbo
1         pegas
2         nacho
3      czarnuch
4        bambus
         ...
723     muslimy
724      kuffar
725     bastard
726    koszerne
727        piky
Length: 728, dtype: object

In [14]:
common.to_csv('omg.csv')

In [16]:
pd.set_option('display.max_rows', 500)

new_data = []
for term in common:
    row = {}
    row['term'] = term
    row['freq'] = main_dict[term]
    new_data.append(row)
df= pd.DataFrame(new_data, columns=['term', 'freq']).sort_values('freq', ascending=False)
df[:100]

         term   freq
174     nicht  39225
686  property  16271
395      avec  15392
652        ka  12559
193    muslim   9413
705     india   4232
720    slaves   3446
18        bor   3034
222      sole   2840
542     queen   2785
97      slave   2518
637    ghetto   2476
365   gypsies   2058
560      bird   1951
209       gay   1942
422        cp   1889
73      gypsy   1872
477        af   1600
530    yellow   1417
258    mongol   1399
9         ned   1392
84      preto   1357
573      homo   1322
221     queer   1229
224      tard   1203
168    fruits   1127
436      nego   1110
654     birds   1098
284      mock   1009
599       tan    979
441     ghost    899
532      turk    895
529       pot    852
196     janet    825
617     judas    822
456    spades    777
659   mongols    773
304       ars    759
331      malo    752
594     shade    739
621      niak    703
66        bog    672
460      eggs    660
24      bonne    657
308    ghosts    628
266       tut    585
39     shades    583
487       yid    559
544       gin    541
146       nig    520
467      nega    491
147     shine    472
402       ola    465
515      albo    443
591     slope    439
513      gora    429
645      prod    422
58      trash    419
450      hora    408
37      domes    397
265    graffy    392
36      dinge    378
566     negro    373
134       hos    372
80     apples    368
105       969    361
273       abd    358
695      gins    339
432    shines    334
259       abo    326
415    ustasa    325
717       786    324
101       zip    310
397     hicks    304
382      zhid    300
371   khazars    294
619     tiger    293
618       def    271
227      arne    267
191     mocks    262
454       kas    262
354    guinea    258
688      bung    253
89      slant    246
166    retard    241
30        yom    238
229       ike    222
261       boo    219
526    khazar    219
524     guido    209
392    queens    208
687    queers    202
626     pussy    202
192     whore    201
725   bastard    186
647      fica    184
468      babi    184
268    slopes    181
644      boon    181
370     hadji    168

In [24]:
terms = """bitch
bitches
blockheads
chink
chinks
cripple
cripples
cunt
darkie
dyke
faggots
fairies
feminazis
gypsies
gypsy
half breeds
hicks
homo
idiots
khokhol
khokhols
kike
kikes
nego
negro
nigger
paki
pizda
pussy
queer
queers
redneck
redskins
retard
retarded
retards
slut
sluts
tar baby
whore
whores
yid
yids
yokel
zhid
zhidovka"""
terms = terms.split('\n')
shared = pd.Series(list(set(df['word']) & set(terms)))

In [25]:
pd.set_option('display.max_rows', 500)

new_data = []
for term in shared:
    row = {}
    row['term'] = term
    row['freq'] = main_dict[term]
    new_data.append(row)
df1= pd.DataFrame(new_data, columns=['term', 'freq']).sort_values('freq', ascending=False)
df1[:100]

           term  freq
39      gypsies  2058
13        gypsy  1872
25         homo  1322
27        queer  1229
29         nego  1110
37          yid   559
12        negro   373
35        hicks   304
11         zhid   300
10       retard   241
33        pussy   202
1        queers   202
44        whore   201
0          yids   161
7        idiots   139
18     retarded   137
45        bitch   128
3       cripple    97
5       khokhol    91
15         dyke    81
31     cripples    75
2        whores    67
32         kike    52
4          paki    50
40        kikes    43
30      retards    41
43      bitches    40
38         slut    35
24      fairies    34
14        chink    29
41        yokel    27
23       nigger    24
16        pizda    23
36       chinks    21
21         cunt    20
34   blockheads    13
17      redneck    13
22      faggots    10
28        sluts     9
8      khokhols     8
9      zhidovka     8
19    feminazis     5
42  half breeds     4
6      redskins     2
20     tar baby     2
26       darkie     1